site_name: CS自学指南
theme:
  name: material
repo_url: https://github.com/pkuflyingpig/pku-cs-self-learning/
nav:
  - 前言: 'index.md'
  - 一个仅供参考的CS学习规划: 'CS学习规划.md'
  - 必学工具:
    - 翻墙: '必学工具/翻墙.md'
    - Vim: '必学工具/Vim.md'
    - Git: '必学工具/Git.md'
    - Github: '必学工具/Github.md'
    - Makefile: '必学工具/Makefile.md'
    - Latex: '必学工具/Latex.md'
    - 实用工具箱: '必学工具/tools.md'
  - 编程入门:
    - MIT-Missing-Semester: '编程入门/MIT-Missing-Semester.md'
    - 'Harvard CS50: This is CS50x': '编程入门/CS50.md'
    - 'UCB CS61A: Structure and Interpretation of Computer Programs': '编程入门/CS61A.md'
    - 'Stanford CS106L: Standard C++ Programming': '编程入门/CS106L.md'
    - 'Stanford CS110L: Safety in Systems Programming': '编程入门/CS110L.md'
  - 数据结构与算法:
    - 'UCB CS61B: Data Structures and Algorithms': '数据结构与算法/CS61B.md'
    - 'Coursera: Algorithms I & II': '数据结构与算法/Algo.md'
    - 'UCB CS170: Efficient Algorithms and Intractable Problems': '数据结构与算法/CS170.md'
  - 体系结构: 
    - 'Coursera: Nand2Tetris': '体系结构/N2T.md'
    - 'UCB CS61C: Great Ideas in Computer Architecture': '体系结构/CS61C.md'
    - 'CMU CS15213: CSAPP': '体系结构/CSAPP.md'
  - 操作系统:
    - 'MIT 6.S081: Operating System Engineering': '操作系统/MIT6.S081.md'
    - 'UCB CS162: Operating System': '操作系统/CS162.md'
  - 计算机网络:
    - 'Computer Networking: A Top-Down Approach': '计算机网络/topdown.md'
    - 'Stanford CS144: Computer Network': '计算机网络/CS144.md'
  - 人工智能:
    - 'Harvard CS50’s Introduction to AI with Python': '人工智能/CS50.md'
    - 'UCB CS188: Introduction to Artificial Intelligence': '人工智能/CS188.md'
  - 机器学习:
    - 'Coursera: Machine Learning': '机器学习/ML.md'
    - 'Stanford CS229: Machine Learning': '机器学习/CS229.md' 
    - 'UCB CS189: Introduction to Machine Learning': '机器学习/CS189.md'
  - 深度学习:
    - 'Coursera: Deep Learning': '深度学习/CS230.md'
    - '台湾国立大学：李宏毅机器学习': '深度学习/LHY.md'
    - 'Stanford CS231n: CNN for Visual Recognition': '深度学习/CS231.md'
    - 'Stanford CS224n: Natural Language Processing': '深度学习/CS224n.md'
    - 'Stanford CS224w: Machine Learning with Graphs': '深度学习/CS224w.md'
    - 'UCB CS285: Deep Reinforcement Learning': '深度学习/CS285.md'